# Abstract 



<!-- 
        #### ------------------ #####
        #### --- GUIDELINES --- #####
        #### ------------------ #####
        
        ## - Saramäki - ##  
        - SETUP 
                -> CONFRONTATION 
                        -> RESOLUTION 
                                -> EPILOGUE 
        ## -- STOTEN -- ## 
        The purpose of the research, the principal results and major conclusions.
        300 words 
--> 

<!-- SETUP --> 
Human actions are altering the composition and functioning of ecological communities globally. 
This transformation is especially rapid and intensive in freshwater ecosystems. 
Comprehensive and international regulatory frameworks are necessary to slow down and halt the current loss of biodiversity. 
These regulatory frameworks, such as the Water Framework Directive (WFD), typically reduce the inherent complexity of their subjects through classification systems that use selected features to classify the subjects into a typology. 
A recently proposed pan-European typology for freshwater systems has unified the assortment of existing national typologies.
However, it lacks biological validation. 
<!-- CONFRONTATION --> 
Using cluster validity analyses, we evaluated whether freshwater macroinvertebrate communities are more similar within then among types. 
To compare the typology's performance, we conducted the same analyses with three additional freshwater typologies.
Beyond the typologies themselves, our analyses enabled us to compare two typologies based on river reaches with those based on ecoregions. 
Lastly, we provide lists of typical macroinvertebrate taxa for the types of each typologies.   
<!-- RESOLUTION --> 
Though performance differed between validity metrics, the newly proposed typology rarely ranked among the best. 
Overall, regional typologies achieved better scores than those based on river reaches.  
However, all typologies failed to achieve high cluster validity scores. 
SART ZU TYPICAL ASSEMBLAGES
<!-- EPILOGIE -->
Our findings indicate that superior alternatives to the new pan-European rivers typology exist but also that none reliably delineate demarcations between internally homogeneous macroinvertebrate reference communities. 
Hence, it remains important to further improve freshwater typologies to improve biomonitoring and facilitate conservation efforts. 
<!-- 

##### ----- OLD DRAFTS ----- ##### 

To reduce the impact of known stressors and prevent the emergence of new ones, comprehensive international regulatory frameworks are necessary. 
The Water Framework Directive (WFD) aims to achieve this for the European Union.
Despite missing its initial target of elevating all waterbodies to good quality in 2015, it has let to considerable progress in our knowledge of European waterbodies as well as new and improved methods for biomonitoring.
Central to the WFD the division of freshwater systems into types, each with different reference conditions. 
While national states use national typologies for their evaluations, a Pan-European typology of rivers has recently been proposed. 
Here we evaluate whether this typology is a good classifications of aquatic macroinvertebrate communities, compare it with other freshwater typologies, and derive typical and indicator taxa for its types.
To this end, we 
All our analyses indicate, that macroinvertebrate differ between some of the proposed types but large redundancies reamin. 


--> 


